js/clientes.js, js/nueva_factura.js, modal/editar_cliente.php, modal/nuevo_cliente.php, nueva_factura.php
**Cliente:**
Nuevo Cliente: Consumo de Api Sectores. Correo no obligatorio.
Editar Cliente: Consumo de Api Sectores. Mostrar el sector del usuario. Correo no obligatorio.
Factura:
Nueva Factura: Sector atado al cliente y des-habilitado.
Agregar (Producto). Seleccionado el precio normal en el momento que escoge la unidad.
=> Modificaciones 18 09 2018

js/nueva_factura.js, js/productos.js, modal/editar_producto.php, modal/nuevo_producto.php, nueva_factura.php, productos.php
Producto
Nuevo producto: con los campos necesarios, se incluye código para que el cliente lo digite.
Consulta Producto: los campos necesarios.
Factura:
Calculo de producto con iva, subtotal y total
=> Cambios en producto y factura nueva

caja_chica.php, js/banco.js, js/caja_chica.js, js/nueva_entrega.js, js/nueva_factura.js
Caja Chica
Listado de Detalle de los egresos
Orden de la lista de la consulta (aun falta)
3 decimales
Quitar la hora de la fecha
=> Caja chica Reunion 14-09-2018

banco.php, js/banco.js, js/caja_chica.js, js/clientes.js, js/facturas.js, js/guia_entrega.js, js/guia_recepcion.js, js/guia_remision.js, js/nueva_entrega.js
Guia de Entrega
Revision del flujo, correcciones.
Caja Chica
Orden DESC por fecha
Banco
Orden DESC por ID
Cliente
Orden DESC por ID
Guias
Orden DESC por ID
Factura
Orden DESC por numero de factura
=> Caja chica, orden en la consultas de guias y factura

js/libro_diario.js, libro_diario.php, modal/nuevo_egreso_libro.php, modal/nuevo_ingreso_libro.php
Nuevo Módulo Libro Diario
Consulta, nuevo ingreso y nuevo egreso
=> Nuevo libro diario

caja_chica.php, js/caja_chica.js, modal/nuevo_egreso.php, modal/nuevo_ingreso.php, modal/nuevo_ingreso_banco.php
Ingreso de Caja chica, se hace un egreso en banco
=> Caja Chica, el ingreso es egreso en Banco

css/nueva_compra.css, js/nueva_factura.js, modal/consultar_productos.php, navbar.php, nueva_factura.php
Consideraciones en nueva factura sin forma de pago
=> Factura fix 1

js/nuevo_personal.js, modal/nuevo_usuario.php, nuevo_personal.php
Personal
Actualizado cargos y relacionado al perfil de usuario
Usuario
Actualizado perfiles de usuario
=> Actulizado cargos y perfil de usuarios

nueva_compra.php
=> disabled total compra

api/compra/getAll.php, api/objects/compra.php, compras.php, js/compras.js
=> lista de compras

inventario.php, js/inventario.js, navbar.php
Nuevo Inventario
Menú
Consulta
=> Inventario Consulta Nuevo

editar_personal.php, nuevo_personal.php
Perfil administrador en nuevo personal y modificación que el cargo estaba con Cargo1, Cargo2,...
=> agregar administrador y modificación perfil

js/clientes.js, js/productos.js, modal/editar_cliente.php, modal/editar_producto.php, modal/nuevo_cliente.php
Nuevo y Modificar Cliente 
-Hacer obligatorio Documento
Order By ID Desc
=> Clientes fix 2

modal/editar_proveedor.php, modal/nuevo_proveedor.php
=> Proveedor no obligatorio tlf de empresa

js/productos.js, modal/nuevo_producto.php
Modificar:
-Habilitar modificación de und caja
Order By ID DESC
=> Producto fix 2

js/caja_chica.js
=> Caja chica fix 2

modal/editar_cliente.php, modal/nuevo_cliente.php
Faltaría, bloquear el botón para no crear dos veces el mismo cliente
=> Cliente No obligatorio razon social ni telefonos

js/caja_chica.js
Mergeo luego de resolver conflictos y errores
=> Libro diario fix 2

api/inventario/getAll.php, api/inventario/getById.php, api/inventario/getByIdProd.php, api/inventario/insert.php, api/inventario/update.php, api/kardex/getAll.php, api/kardex/getByIdProd.php, api/kardex/getByProducto.php, api/kardex/getIdMax.php, api/libroDiario/getAll.php, api/libroDiario/getById.php, api/objects/cliente.php, api/objects/inventario.php, api/objects/kardex.php, api/objects/libroDiario.php, api/objects/personal.php, api/objects/producto.php, api/producto/getByCodigoFactura.php, css/nueva_compra.css, editar_factura.php, js/editar_factura.js, js/nueva_factura.js, nueva_factura.php
Faltante quitar horas del detalle de factura y colocar botón imprimir afuera.
=> Facturas fix 2

js/clientes.js, js/nuevo_personal.js, js/productos.js, js/proveedores.js, modal/editar_proveedor.php, modal/nuevo_proveedor.php, proveedores.php
=> Proveedor fix 3

js/config.js
=> Config.js url api/

css/custom.css, editar_personal.php, js/productos.js, js/usuarios.js, modal/cambiar_password.php, modal/editar_cliente.php, modal/editar_producto.php, modal/editar_proveedor.php, modal/editar_usuarios.php, modal/nuevo_cliente.php, modal/nuevo_egreso.php, modal/nuevo_egreso_banco.php, modal/nuevo_ingreso.php, modal/nuevo_ingreso_banco.php, modal/nuevo_producto.php, modal/nuevo_proveedor.php, modal/nuevo_usuario.php, nueva_compra.php, nuevo_personal.php
En campos obligatorios *Rojo y placeholder en los formularios
=> *rojo y placeholder

api/compra/getAll.php, api/config/database.php, api/objects/compra.php
=> apis actualizadas

clientes.php, js/banco.js, js/clientes.js, js/compras.js, js/facturas.js, js/nueva_factura.js, js/productos.js, modal/consultar_clientes.php, modal/editar_producto.php, nueva_factura.php
=> Compras fix 4

inventario.php, js/inventario.js, js/nueva_factura.js, nueva_compra.php, print/factura.php
Formato de impresión factura
Inventario mostrar ppp ind, pvt ind, ppp total, pvt total
=> Impresion factura
